// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using clashCommunity_api.Tools;

#nullable disable

namespace clashCommunity_api.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20221215115035_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("clashCommunity_api.Models.Clan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clan");
                });

            modelBuilder.Entity("clashCommunity_api.Models.RoleApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RoleApp");
                });

            modelBuilder.Entity("clashCommunity_api.Models.Userapp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("CanApprove")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_approve");

                    b.Property<int>("ClanId")
                        .HasColumnType("int")
                        .HasColumnName("clan_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<int>("RoleAppId")
                        .HasColumnType("int")
                        .HasColumnName("roleapp_id");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tag");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.HasIndex("RoleAppId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("clashCommunity_api.Models.Userapp", b =>
                {
                    b.HasOne("clashCommunity_api.Models.Clan", "Clan")
                        .WithMany()
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("clashCommunity_api.Models.RoleApp", "RoleApp")
                        .WithMany()
                        .HasForeignKey("RoleAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");

                    b.Navigation("RoleApp");
                });
#pragma warning restore 612, 618
        }
    }
}
